### ISSUE TITLE
Asset references are serialized as null 

### ISSUE THREAD

**Issue by marthinfreij** [contentful/contentful-management.objc#10]
I'm trying to fetch an entry with ```[space fetchEntriesMatching: success: failure:]```, make some changes and then ```[entry updateWithSuccess: failure:]```, but I'm getting *Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (CMAAsset)'*

My entry has a to-many relation to Asset, and when I inspect the entry, I can see that the asset references are serialized as null

```
photos =     (
        (null),
        (null)
    );
```

I think the issue is somewhere near ```CDAAsset``` ```initWithDictionary: client:``` where it expect dictionary to have a fields key, but it's missing because it's just a reference.

**Comment by neonichu** [comment]
I think this is actually the same issue as #9 — will know once I investigate this a bit further.

**Comment by neonichu** [comment]
I have pushed a fix for #9 now, could you check if this had indeed the same cause?

**Comment by neonichu** [comment]
Closing as this has most likely been fixed by #9
