### ISSUE TITLE
Cocoapod doesn't build

### ISSUE THREAD

**Issue by bentrengrove** [contentful/contentful-management.objc#13]
Started a new Objc iOS project and added the CocoaPod. Getting a build error. The only thing I have done is add the Pod and attempted to build, the project is from the single view template.

![screen shot 2016-06-02 at 08 51 18](https://cloud.githubusercontent.com/assets/19445/15728366/4bff1a18-289f-11e6-8d48-2e5b49d47f8e.png)

Podfile

> platform :ios, '9.0'
> target 'StarlingManagement' do
> pod 'ContentfulManagementAPI'
> end

Pod install

> Analyzing dependencies
> Downloading dependencies
> Installing AFNetworking (2.5.4)
> Installing ContentfulDeliveryAPI (1.10.3)
> Installing ContentfulManagementAPI (0.7.0)
> Installing ISO8601DateFormatter (0.7)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.

I did a very quick debug attempt and it looks like the initializer needs the `localizationAvailable` parameter. Has CocoaPods resolved the wrong version?

Any ideas? Thanks, Ben

**Comment by neonichu** [comment]
Sorry about this, I missed that this change in the CDA SDK is a breaking change for the CMA. You can temporarily work around it by pinning ContentfulDeliveryAPI to 1.10.1 in your Podfile.

**Comment by bentrengrove** [comment]
No problem. Will do!

**Comment by neonichu** [comment]
Fixed in d6078ee9b712396629f51ad04e8570dadb843f75

Shipped as part of 0.7.1
