### ISSUE TITLE
CMASpace's fetchContentTypeWithIdentifier:success:failure: method doesn't work

### ISSUE THREAD

**Issue by graemesi** [contentful/contentful-management.objc#8]
The CMASpace method fetchContentTypeWithIdentifier:success:failure: doesn't work - it always returns
Error: Error Domain=CDAErrorDomain Code=0 "No Resources matched your query.

Example:

```objective-c
- (void)uploadToContentful {
    [self.client fetchAllSpacesWithSuccess:^(CDAResponse *response, CDAArray *array) {
        for (CMASpace *space in array.items) {
            if ([space.name isEqualToString:@"My test space"]) {
                [self uploadToMyTestSpace:space];
                break;
            }
        }
    } failure:^(CDAResponse *response, NSError *error) {
        NSLog(@"Error: %@", error);
    }];
}


- (void)uploadToMyTestSpace:(CMASpace *)space {
    [space fetchContentTypeWithIdentifier:@"Recipe"
                                  success:^(CDAResponse *response, CMAContentType *type) {
                                      NSLog(@"%@", type);
                                  } failure:^(CDAResponse *response, NSError *error) {
                                      // This failure block is always called
                                      NSLog(@"Error: %@", error);
                                  }];
}
```

Note: When I set a breakpoint in CDAContentTypeRegistry's contentTypeForIdentifier: method, I've noticed self.contentTypes has 0 key/value pairs. So it looks like the content types aren't being registered.

**Comment by neonichu** [comment]
The problem is most probably that "Recipe" is not an identifier, but a name of a content type. You can find the identifier in the web UI by clicking "Info" when you are looking at that content type.

**Comment by graemesi** [comment]
Yes you're right, that was the problem. I misunderstood the documentation.
